name: Hello World Workflow GithubAction

on: 
  push:
    branches:
      - main

jobs:
  say_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World!
        run: echo "Hello, World! github action"

